spring:
  application:
    name: day1
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    show_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

server:
  port: 8080


app:
  jwt:
    issuer: yoedu-demo
    secret: 01234567890123456789012345678912
    access-token-ttl-minutes: 480
    refresh-token-ttl-days: 7
